# Project information
site_name: Tatsuki Tsujimoto
site_description: My personal website with all information about me.
site_url: https://ttktjmt.com/

# Repository
repo_name: ttktjmt/ttktjmt.com
repo_url: https://github.com/ttktjmt/ttktjmt.com

# Copyright
copyright: '&copy;2024 Tatsuki Tsujimoto'

# Configuration
theme:
  name: material
  logo: img/terminal-solid.svg
  favicon: img/terminal-solid.svg
  language: en
  features:
  - header.links
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.tooltips
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.indexes
  - navigation.path
  - navigation.tabs
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: lime
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: cyan
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - blog:
      draft_on_serve: false
      post_url_format: "{slug}"
  - social: # dependencies issue: https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/#cairo-graphics-macos
  # the `mkdocs gh-deploy` command used in the "GitHub Pages Update" workflow sets the metadata of social card image with the property="og:image" to the "ttktjmt.com" URL, not the "ttktjmt.github.io/tktjmt.com" URL even when I deploy this on the GitHub Pages.
  # So, the social card only works when this site is deployed under the "ttktjmt.com" URL.

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ttktjmt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tatsukitsujimoto
    - icon: fontawesome/solid/code
      link: https://leetcode.com/ta747375ki

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Page tree
nav:
- Home: index.md
- About:
  - Overview: about/overview.md
  - Versioning: about/versioning.md
  - CI/CD: about/cicd.md
- Projects: projects.md
- Experience: experience.md
- Education: education.md
- Blog:
  - blog/index.md
- Contact: contact.md
